/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.ct.client.view;

import cn.ct.client.App;
import cn.ct.client.frm.CreateProjectDialog;
import cn.ct.model.Info;
import cn.ct.model.ObjectWrapper;
import cn.ct.model.Project;
import cn.ct.model.User;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author cn200
 */
public class CreateProjectPanel extends javax.swing.JPanel {

    private CreateProjectDialog parent;
    /**
     * Creates new form CreateProjectPanel
     */
    public CreateProjectPanel(CreateProjectDialog parent) {
        this.parent = parent;
        initComponents();
        
        tvMessage.setText("");
        edtProj.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateView();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateView();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateView();
            }
        });
    }
    
    private void updateView() {
        edtOutput.setText(edtDir.getText() + "\\" + edtProj.getText());
        if (edtDir.getText().isBlank() || edtDir.getText().isEmpty() 
                || edtProj.getText().isBlank() || edtProj.getText().isEmpty()) {
            btnCreate.setEnabled(false);
            return;
        }
        if (new java.io.File(edtOutput.getText()).exists()) {
            tvMessage.setText("Folder \"" + edtProj.getText() + "\" is exists.");
            btnCreate.setEnabled(false);
        } else {
            tvMessage.setText("");
            btnCreate.setEnabled(true);
        }
    }
    
    private void createProjectResult(ObjectWrapper data) {
        if (data.getMessage() == ObjectWrapper.MES_SUCCESS) {
            JOptionPane.showMessageDialog(this, "Create project successfully.");
            parent.close();
        } else {
            JOptionPane.showMessageDialog(this, "Create project failed.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDir = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        tvMessage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtOutput = new javax.swing.JTextField();
        edtProj = new javax.swing.JTextField();
        edtDir = new javax.swing.JTextField();

        btnDir.setText("...");
        btnDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.setEnabled(false);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        tvMessage.setForeground(new java.awt.Color(255, 0, 0));
        tvMessage.setText("Sample message");

        jLabel4.setText("Directory:");

        jLabel5.setText("Project name:");

        jLabel6.setText("Output folder:");

        edtOutput.setEditable(false);

        edtDir.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edtDir, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDir))
                            .addComponent(edtProj)
                            .addComponent(edtOutput)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tvMessage, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnDir)
                    .addComponent(edtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edtProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirActionPerformed
        // TODO add your handling code here:
        JFileChooser f = new JFileChooser();
        if (!edtDir.getText().isEmpty()) {
            f.setCurrentDirectory(new java.io.File(edtDir.getText()));
        }
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showDialog(this, "Open");
        
        edtDir.setText(f.getSelectedFile().getAbsolutePath());
        updateView();
    }//GEN-LAST:event_btnDirActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        App.ctrl.sendData(new ObjectWrapper(ObjectWrapper.GET_CREATE_PROJECT, 
                    new Project(0, null, null, new Info(0, edtProj.getText(), null, null))))
                .register(ObjectWrapper.REPLY_CREATE_PROJECT, data -> {
            createProjectResult(data);
        });
    }//GEN-LAST:event_btnCreateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDir;
    private javax.swing.JTextField edtDir;
    private javax.swing.JTextField edtOutput;
    private javax.swing.JTextField edtProj;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel tvMessage;
    // End of variables declaration//GEN-END:variables
}
