/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.ct.client.view;

import cn.ct.client.App;
import cn.ct.client.frm.ListCollabDialog;
import cn.ct.client.util.SomeFunc;
import cn.ct.model.Collab;
import cn.ct.model.ObjectWrapper;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cn200
 */
public class ListCollabPanel extends javax.swing.JPanel {

    private ListCollabDialog parent;
    private List<Collab> collabs;
    private int selectedCollab = -1;
    
    /**
     * Creates new form ListCollabPanel
     */
    public ListCollabPanel(ListCollabDialog parent) {
        this.parent = parent;
        initComponents();
        collabs = new ArrayList<>();
        
        App.ctrl.sendData(new ObjectWrapper(ObjectWrapper.GET_LIST_INVITE, null))
                .register(ObjectWrapper.REPLY_LIST_INVITE, data -> {
            listCollabResult(data);
        });
    }
    
    private void updateView() {
        String[] columnNames = {"Id", "Project name", "Host", "Create time"};
        String[][] value = new String[collabs.size()][columnNames.length];
        for (int i = 0; i < collabs.size(); ++i) {
            value[i][0] = String.valueOf(i + 1);
            value[i][1] = collabs.get(i).getFromProject().getInfo().getName();
            value[i][2] = collabs.get(i).getFromProject().getHost().getName();
            value[i][3] = SomeFunc.formatDate(collabs.get(i).getFromProject().getInfo().getCreateTime());
        }
        
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        tb.setModel(tableModel);
        tb.getColumnModel().getColumn(0).setPreferredWidth(10);
        tb.getColumnModel().getColumn(1).setPreferredWidth(100);
        tb.getColumnModel().getColumn(2).setPreferredWidth(100);
        tb.getColumnModel().getColumn(3).setPreferredWidth(65);
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    
    private void listCollabResult(ObjectWrapper data) {
        if (data.getMessage() == ObjectWrapper.MES_SUCCESS) {
            collabs = (List<Collab>) data.getData();
            updateView();
        }
    }
    
    private void acceptCollabResult(ObjectWrapper data) {
        if (data.getMessage() == ObjectWrapper.MES_SUCCESS) {
//            JFileChooser f = new JFileChooser();
//            Collab collab = (Collab) data.getData();
//            f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//            while (true) {
//                f.showDialog(this, "Save " + collab.getFromProject().getInfo().getName());
//                if (!new java.io.File(f.getSelectedFile().getAbsoluteFile() 
//                    + "\\" + collab.getFromProject().getInfo().getName()).exists()) {
//                    JOptionPane.showMessageDialog(this, "Error while accept invitation.", 
//                            "Message", JOptionPane.ERROR_MESSAGE);
//                    continue;
//                }
//                break;
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Error while accept invitation.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void rejectCollabResult(ObjectWrapper data) {
        if (data.getMessage() == ObjectWrapper.MES_FAILED) {
            JOptionPane.showMessageDialog(this, "Error while reject invitation.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb);

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAccept))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnReject))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int row = tb.getSelectedRow();
        
        if (row >= 0 && row < collabs.size()) {
            App.ctrl.sendData(new ObjectWrapper(ObjectWrapper.GET_ACCEPT_COLLAB, collabs.get(row)))
                    .register(ObjectWrapper.REPLY_ACCEPT_COLLAB, data -> {
                acceptCollabResult(data);
            });
            collabs.remove(row);
            updateView();
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int row = tb.getSelectedRow();
        
        if (row >= 0 && row < collabs.size()) {
            App.ctrl.sendData(new ObjectWrapper(ObjectWrapper.GET_REJECT_COLLAB, collabs.get(row)))
                    .register(ObjectWrapper.REPLY_REJECT_COLLAB, data -> {
                rejectCollabResult(data);
            });
            collabs.remove(row);
            updateView();
        }
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
