/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.ct.client.view;

import cn.ct.client.App;
import cn.ct.client.frm.ListProjectDialog;
import cn.ct.client.util.SomeFunc;
import cn.ct.model.ObjectWrapper;
import cn.ct.model.Project;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cn200
 */
public class ListProjectPanel extends javax.swing.JPanel {
    
    private ListProjectDialog parent;
    private boolean isCollab;
    private List<Project> projects;

    /**
     * Creates new form OpenProjectPanel
     */
    public ListProjectPanel(ListProjectDialog parent, boolean isCollab) {
        this.parent = parent;
        this.isCollab = isCollab;
        initComponents();
        projects = new ArrayList<>();
        updateView();
        
        if (isCollab) {
            App.ctrl.sendData(new ObjectWrapper(ObjectWrapper.GET_COLLAB_PROJECT, null))
                    .register(ObjectWrapper.REPLY_COLLAB_PROJECT, data -> {
                listProjectResult(data);
            });
        } else {
            App.ctrl.sendData(new ObjectWrapper(ObjectWrapper.GET_LIST_PROJECT, null))
                    .register(ObjectWrapper.REPLY_LIST_PROJECT, data -> {
                listProjectResult(data);
            });
        }
    }
    
    private void updateView() {
        String[] columnNames = {"Id", "Project name", "Create time", "Version code"};
        String[][] value = new String[projects.size()][columnNames.length];
        for (int i = 0; i < projects.size(); ++i) {
            value[i][0] = String.valueOf(i + 1);
            value[i][1] = projects.get(i).getInfo().getName();
            value[i][2] = SomeFunc.formatDate(projects.get(i).getInfo().getCreateTime());
            value[i][3] = projects.get(i).getInfo().getVersion();
        }
        
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        tb.setModel(tableModel);
        tb.getColumnModel().getColumn(0).setPreferredWidth(10);
        tb.getColumnModel().getColumn(1).setPreferredWidth(100);
        tb.getColumnModel().getColumn(2).setPreferredWidth(65);
        tb.getColumnModel().getColumn(3).setPreferredWidth(200);
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    
    private void listProjectResult(ObjectWrapper data) {
        if (data.getMessage() == ObjectWrapper.MES_SUCCESS) {
            projects = (List<Project>) data.getData();
            updateView();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btnOpen = new javax.swing.JButton();

        jLabel1.setText("Your projects:");

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb);

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOpen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpen)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        int row = tb.getSelectedRow();
        
        if (row >= 0 && row < projects.size()) {
            App.ctrl.sendData(new ObjectWrapper(ObjectWrapper.GET_OPEN_PROJECT, 
                    projects.get(row)));
            parent.close();
        }
    }//GEN-LAST:event_btnOpenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
