/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.ct.client.view;

import cn.ct.client.App;
import cn.ct.client.frm.SendCollabDialog;
import cn.ct.model.Collab;
import cn.ct.model.ObjectWrapper;
import cn.ct.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author cn200
 */
public class SendCollabPanel extends javax.swing.JPanel {

    private SendCollabDialog parent;
    
    /**
     * Creates new form SendInvitationPanel
     */
    public SendCollabPanel(SendCollabDialog parent) {
        this.parent = parent;
        initComponents();
    }
    
    private void sendCollabResult(ObjectWrapper data) {
        if (data.getMessage() == ObjectWrapper.MES_SUCCESS) {
            JOptionPane.showMessageDialog(this, "Send invitation successfully.");
            edtUsername.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Username is not exist.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edtUsername = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();

        jLabel1.setText("Invite a user to this project:");

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(edtUsername)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSend)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSend)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if (edtUsername.getText().isBlank() || edtUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username can not empty.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
        } else {
            if (edtUsername.getText().equals(App.user.getUsername())) {
                JOptionPane.showMessageDialog(this, "You can not send invitaiton to myself.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
            } else {
                App.ctrl.sendData(new ObjectWrapper(ObjectWrapper.GET_SEND_COLLAB, 
                            new Collab(0, new User(0, null, edtUsername.getText(), null), App.project, false)))
                        .register(ObjectWrapper.REPLY_SEND_COLLAB, data -> {
                    sendCollabResult(data);
                });
            }
        }
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JTextField edtUsername;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
