/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.ct.client.view;

import cn.ct.client.App;
import cn.ct.client.frm.SignupDialog;
import cn.ct.model.ObjectWrapper;
import cn.ct.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author cn200
 */
public class SignupPanel extends javax.swing.JPanel {
    
    private SignupDialog parent;

    /**
     * Creates new form SignupPanel
     */
    public SignupPanel(SignupDialog parent) {
        this.parent = parent;
        initComponents();
    }
    
    private void signupResult(ObjectWrapper data) {
        if (data.getMessage() == ObjectWrapper.MES_SUCCESS) {
            JOptionPane.showMessageDialog(this, "Sign up successfully.");
            parent.close();
        } else {
            JOptionPane.showMessageDialog(this, "Sign up failed. Try with another username.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtConfirmPassword = new javax.swing.JPasswordField();
        edtPassword = new javax.swing.JPasswordField();
        edtUsername = new javax.swing.JTextField();
        edtName = new javax.swing.JTextField();
        btnSignup = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jLabel1.setText("Name:");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jLabel4.setText("Confirm password:");

        btnSignup.setText("Sign up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        btnClear.setText("Clear data");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtConfirmPassword)
                            .addComponent(edtPassword)
                            .addComponent(edtUsername)
                            .addComponent(edtName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 175, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignup)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignup)
                    .addComponent(btnClear))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        edtName.setText("");
        edtUsername.setText("");
        edtPassword.setText("");
        edtConfirmPassword.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        if (edtUsername.getText().isEmpty() || edtUsername.getText().isBlank()
                || new String(edtPassword.getPassword()).isEmpty() 
                || new String(edtPassword.getPassword()).isBlank()) {
            JOptionPane.showMessageDialog(this, "Username or password can not empty.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
        } else if (edtUsername.getText().length() < 6 || edtUsername.getText().length() > 32 
                || new String(edtPassword.getPassword()).length() < 6 
                || new String(edtPassword.getPassword()).length() > 32) {
            JOptionPane.showMessageDialog(this, "Username or password must have 6-32 characters.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
        } else if (!new String(edtPassword.getPassword())
                .equals(new String(edtConfirmPassword.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Password and confirm password do not match.", 
                    "Message", JOptionPane.ERROR_MESSAGE);
        } else {
            App.ctrl.sendData(new ObjectWrapper(ObjectWrapper.GET_SIGNUP, 
                        new User(edtName.getText(), edtUsername.getText(), new String(edtPassword.getPassword()))))
                    .register(ObjectWrapper.REPLY_SIGNUP, data -> {
                signupResult(data);
            });
        }
    }//GEN-LAST:event_btnSignupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSignup;
    private javax.swing.JPasswordField edtConfirmPassword;
    private javax.swing.JTextField edtName;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JTextField edtUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
